[package]
name = "imserious"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
axum = "0.5.3"
derive_more = "0.99.17"
humantime-serde = "1.1.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
shell-words = "1.1.0"
tokio = { version = "1.17.0", features = ["macros", "net", "process", "rt", "signal", "sync", "time"] }
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[profile.release]
opt-level = "s"
lto = "thin"
